declare module '*.png';
declare module '*.svg';
declare module '*.jpg';
declare module '*.ico';
// declare module 'electron-store';
declare module 'react-modal';
declare module 'mdbreact';
declare module 'mui-editable-table';
declare module 'material-ui/styles/MuiThemeProvider';
declare module 'smart-timeout';